// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "ALFA",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body dir="rtl" className=" h-screen flex flex-col p-2 px-5">
//         {children}
//         <div id="modal-root"></div>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body dir="rtl" className="{inter.className}  h-screen flex flex-col p-2 px-5">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <div id="modal-root"></div>
        </ThemeProvider>
      </body>
    </html>
  )
}