import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/Header';
import Footer from '@/components/Footer';




export const metadata: Metadata = {
  title: 'ALFA',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


      <body dir="rtl" className="px-12 py-4 overflow-x-hidden">
        <header className="flex items-center justify-between w-full overflow-hidden">
          <Header />
        </header>
        <main>{children}</main>
        <footer className="rounded-3xl bg-[#F9F9F9] w-full px-7 py-8 flex flex-col gap-12">
          <Footer />
        </footer>


        <div id="modal-root"></div>
      </body>
    </html>
  );
}